kind: pipeline
name: default
type: docker

concurrency:
  limit: 1

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: install-unreal-archive
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    commands:
      - apt update && apt install -y curl unzip
      - curl https://code.shrimpworks.za.net/artefacts/net/shrimpworks/unreal-archive/latest/unreal-archive-latest.zip -o unreal-archive-latest.zip
      - unzip unreal-archive-latest.zip
      - mv unreal-archive/* /tmp/ua/
#    when:
#      event:
#        - pull_request

  - name: verify
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    commands:
      - /tmp/ua/bin/unreal-archive summary --content-path=./ --store=NOP
#    when:
#      event:
#        - pull_request

  - name: publish
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    environment:
      SITE_URL: https://unrealarchive.org
      PUB_USER:
        from_secret: PUB_USER
      PUB_KEY:
        from_secret: PUB_KEY
      PUB_HOST:
        from_secret: PUB_HOST
      PUB_ROOT:
        from_secret: PUB_ROOT
    commands:
      - apt update && apt install -y rsync openssh-client
      - ./bin/publish.sh ./
    when:
      ref:
        - refs/heads/master

  - name: sync-search
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    environment:
      SITE_URL: https://unrealarchive.org
      MSE_CONTENT_URL: https://unrealarchive.org/search/api/ua
      MSE_CONTENT_TOKEN:
        from_secret: MSE_TOKEN
      MSE_WIKI_URL: https://unrealarchive.org/search/api/uaw
      MSE_WIKI_TOKEN:
        from_secret: MSE_TOKEN
    commands:
      - /tmp/ua/bin/unreal-archive search-submit --content-path=./ --store=NOP
    when:
      ref:
        - refs/heads/master

volumes:
  - name: ua-bin-cache
    temp: {}
