kind: pipeline
name: default
type: docker

concurrency:
  limit: 1

steps:
  - name: verify
    image: azul/zulu-openjdk-debian:17-latest
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    commands:
      - ./bin/verify.sh ./
    when:
      event:
        - pull_request

  - name: publish
    image: azul/zulu-openjdk-debian:17-latest
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    environment:
      SITE_URL: https://unrealarchive.org
      PUB_USER:
        from_secret: PUB_USER
      PUB_KEY:
        from_secret: PUB_KEY
      PUB_HOST:
        from_secret: PUB_HOST
      PUB_ROOT:
        from_secret: PUB_ROOT
    commands:
      - apt update && apt install -y rsync openssh-client
      - ./bin/publish.sh ./
    when:
      ref:
        - refs/heads/master

  - name: sync-search
    image: azul/zulu-openjdk-debian:17-latest
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    environment:
      SITE_URL: https://unrealarchive.org
      MSE_URL: https://unrealarchive.org/search/api
      MSE_TOKEN:
        from_secret: MSE_TOKEN
    commands:
      - ./bin/sync-search.sh ./
    when:
      ref:
        - refs/heads/master

volumes:
  - name: ua-bin-cache
    temp: {}
