kind: pipeline
name: default
type: docker

concurrency:
  limit: 1


clone:
  depth: 1
  retries: 2

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: install-unreal-archive
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
      - name: apt-cache
        path: /var/cache/apt
    commands:
      - apt update && apt install -y curl
      - curl https://code.shrimpworks.za.net/artefacts/org/unrealarchive/www/latest/www-latest.tgz -o www-latest.tgz
      - tar xzf www-latest.tgz
      - mv unreal-archive-www/* /tmp/ua/

  - name: verify
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
    commands:
      - /tmp/ua/bin/www summary --content-path=./ --store=NOP
    when:
      event:
        - pull_request

  - name: publish
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
      - name: apt-cache
        path: /var/cache/apt
    environment:
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      LC_ALL: "en_US.UTF-8"
      SITE_URL: https://unrealarchive.org
      PUB_USER:
        from_secret: PUB_USER
      PUB_KEY:
        from_secret: PUB_KEY
      PUB_HOST:
        from_secret: PUB_HOST
      PUB_ROOT:
        from_secret: PUB_ROOT
    commands:
      - apt update && apt install -y rsync openssh-client locales-all
      - ./bin/publish.sh ./
    when:
      ref:
        - refs/heads/master

  - name: sync-search
    image: debian:bullseye-slim
    volumes:
      - name: ua-bin-cache
        path: /tmp/ua/
      - name: apt-cache
        path: /var/cache/apt
    environment:
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      LC_ALL: "en_US.UTF-8"
      SITE_URL: https://unrealarchive.org
      MES_CONTENT_URL: https://unrealarchive.org/search/api/ua
      MES_CONTENT_TOKEN:
        from_secret: MSE_TOKEN
      MES_WIKI_URL: https://unrealarchive.org/search/api/uaw
      MES_WIKI_TOKEN:
        from_secret: MSE_TOKEN
    commands:
      - apt update && apt install -y locales-all
      - /tmp/ua/bin/www search-submit --content-path=./ --store=NOP
    when:
      ref:
        - refs/heads/master

volumes:
  - name: ua-bin-cache
    temp: {}
  - name: apt-cache
    temp: {}
