--- !<MUTATOR>
contentType: "MUTATOR"
firstIndex: "2023-02-11 23:06"
game: "Unreal Tournament 2004"
name: "Allows you to configure your amount of Grenades after Spawn!"
author: "Unknown"
description: ""
releaseDate: "2004-04"
attachments: []
originalFilename: "spawngrenades.rar"
hash: "47bd76e5d403ddf9f52128d0c6e0c1ee02819f42"
fileSize: 1654
files:
- name: "SpawnGrenades.u"
  fileSize: 2209
  hash: "93237bba75a983e102ddfa7ecdba5f19f3f196e9"
otherFiles: 2
dependencies: {}
downloads:
- url: "https://f002.backblazeb2.com/file/unreal-archive-files/Unreal%20Tournament%202004/Mutators/A/4/7/bd76e5/spawngrenades.rar"
  main: true
  repack: false
  state: "OK"
links: {}
deleted: false
mutators:
- name: "Allows you to configure your amount of Grenades after Spawn!"
  description: ""
weapons: []
vehicles: []
hasConfigMenu: false
hasKeybinds: false
